// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { FC } from 'react'

type SandBoxInfo = { name: string; location: string; component: FC };const data: SandBoxInfo[] = [];
export default data;