import { Extension } from '../type/type';
import { getNoTextIfJs } from '../utils/string';
import SandboxString from './SandboxString';

class SandboxFilesContent {
  private paths: string[];

  private extension: Extension = 'ts';

  private getFileStart = () =>
    `// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.` +
    `\n` +
    `/* eslint global-require: off */` +
    `${getNoTextIfJs(this.extension)(
      "\nimport { FC } from 'react'\ntype SandBoxInfo = { name: string; location: string; component: FC };"
    )}`;

  private fileEnd = '\nexport default data;';

  constructor(paths: string[], extension: Extension) {
    this.paths = paths;
    this.extension = extension;
  }

  get content() {
    return this.getFileStart() + this.getData() + this.fileEnd;
  }

  private getData = () =>
    `\nconst data${getNoTextIfJs(this.extension)(
      ': SandBoxInfo[]'
    )} = [${this.getSandboxDataList()}];`;

  private getSandboxDataList = () =>
    this.paths.map((path) => SandboxString.new(path).string);
}

export default SandboxFilesContent;
